packages:
  - packages/scene-graph
  - packages/pen
  - packages/kiwi
  - packages/fig
  - packages/core
  - packages/dom-css
  - packages/vue

allowBuilds:
  '@firebase/util': false
  core-js: false
  esbuild: true
  protobufjs: false
  vue-demi: false
